# Site Settings
title: "Dr. Sumita Majhi"
title_separator: "-"
name: &name "Sumita Majhi"
description: &description "PhD in CSE from IITG"
url: https://sumitamajhi.github.io
baseurl: ""
repository: "sumitamajhi/sumitamajhi.github.io/master"

# Site Author - This appears in the sidebar
author:
  name: "Sumita Majhi"
  avatar: "master/images/profile.jpg"
  bio: "PhD in CSE from IITG"
  location: "Guwahati, India"
  employer:
  pubmed:
  googlescholar: "https://scholar.google.com/citations?user=COuTdNkAAAAJ&hl=en&oi=ao"
  email: "sumit176101013@iitg.ac.in"
  researchgate:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "sumitamajhi"
  google_plus:
  keybase:
  instagram:
  impactstory:
  lastfm:
  linkedin: "sumita123.87"
  orcid: "https://orcid.org/0000-0001-7364-8615"
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter: "https://x.com/sumitamajhi11"
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:
Update personal information
