# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Dr. Sumita Majhi
first_name: Sumita
middle_name: 
last_name: Majhi
description: >
  PhD in Computer Science & Engineering from IIT Guwahati. 
  Researcher in 5G/6G Wireless Networks, NOMA, Channel Estimation, and AI/ML for wireless communications.
keywords: 5G, 6G, NOMA, wireless communications, channel estimation, AI/ML, IIT Guwahati, computer science
lang: en
icon: ⚡

url: "https://sumitamajhi.github.io"
baseurl: ""

# -----------------------------------------------------------------------------
# Social profiles
# -----------------------------------------------------------------------------
github_username: sumitamajhi
email: sumit176101013@iitg.ac.in
linkedin_username:  # Add your LinkedIn username if available
google_scholar_id:  # Add your Google Scholar ID if available

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: false
search_enabled: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
max_width: 930px

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Research Blog
blog_description: Latest research updates and publications
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-paginate
  - jekyll-archives

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------
scholar:
  style: ieee
  locale: en
  source: ./_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  
  replace_strings: true
  join_strings: true
  
  details_dir: bibliography
  details_link: Details
  
  query: "@*"
  group_by: year
  group_order: descending

# Display publication badges
enable_publication_badges:
  altmetric: false
  dimensions: false
  google_scholar: true

# Maximum authors to show
max_author_limit: 3

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_math: true
enable_darkmode: true
enable_progressbar: true
enable_masonry: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# Sitemap
# -----------------------------------------------------------------------------
sass:
  style: compressed

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------
jekyll-archives:
  enabled: [year, tags]
  layouts:
    year: archive
    tag: archive
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'

# -----------------------------------------------------------------------------
# External services (optional - configure later)
# -----------------------------------------------------------------------------
# google_analytics: 
# disqus_shortname: 

# -----------------------------------------------------------------------------
# Footer
# -----------------------------------------------------------------------------
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

back_to_top: true
last_updated: false
