# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Dr. Sumita Majhi
first_name: Sumita
middle_name: 
last_name: Majhi
contact_note: >
  Feel free to reach out for research collaborations or academic discussions.
description: >
  PhD in Computer Science & Engineering from IIT Guwahati. Researcher in 5G/6G Wireless Networks, NOMA, Channel Estimation, and AI/ML for wireless communications.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: 5G, 6G, NOMA, wireless communications, channel estimation, AI/ML, IIT Guwahati
lang: en
icon: ⚡

# UPDATE THIS CRITICAL LINE:
url: https://sumitamajhi.github.io
baseurl: ""  # Leave empty for root domain

# -----------------------------------------------------------------------------
# Social profiles - UPDATE THESE
# -----------------------------------------------------------------------------
github_username: sumitamajhi
email: sumit176101013@iitg.ac.in
